# @package _global_
# Pendulum-v1. Continuous 1-D action; 3-D observation.

defaults:
  - /transform@transform_noop_reset: noop_reset
  - /transform@transform_step_counter: step_counter
  - /transform@transform_reward_sum: reward_sum
  - /env@training_env: batched_env
  - /env@training_env.create_env_fn: transformed_env
  - /env@training_env.create_env_fn.base_env: gym
  - /transform@training_env.create_env_fn.transform: compose

env:
  obs_dim: 3
  action_dim: 1
  policy_out_dim: 2  # 2 * action_dim for tanh_normal (loc, scale)

transform_noop_reset:
  noops: 30
  random: true

transform_step_counter:
  max_steps: 200
  step_count_key: step_count

transform_reward_sum:
  in_keys: [reward]
  out_keys: [reward_sum]

training_env:
  num_workers: 1
  create_env_fn:
    base_env:
      env_name: Pendulum-v1
    transform:
      transforms:
        - ${transform_noop_reset}
        - ${transform_step_counter}
        - ${transform_reward_sum}
    _partial_: true
