defaults:
  - _self_
  - paths: default
  - algorithm: ???
  - environment: ???
  - logger: []
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

trainer:
  _target_: src.trainers.StepTrainer
  accelerator: cpu
  devices: [0]
  seed: 42
  total_frames: 0          # not used for eval, but required by trainer
  num_envs: 1
  log_every_n_steps: 1_000
  num_eval_episodes: 10

checkpoint:
  resume_from: ???        # required: path to checkpoint file

hydra:
  run:
    dir: ${paths.log_dir}/eval/runs/${now:%Y-%m-%d_%H-%M-%S}
